add env variable to disable rc check

diff --git a/_shims/go b/_shims/go
--- a/_shims/go
+++ b/_shims/go
@@ -28,27 +28,29 @@ localdir="$PWD"
 [[ -f "$localdir/.rodentrc" ]] && {
   allow_local_rc=true
 
-  if ! grep -Fxqs "$localdir" "$RODENT_HOME/local/trusted-paths"
-  then
-    echo "!!! Untrusted rodentrc found at $localdir !!!"
-    read -p "Trust location and load? " -n 1 -r
-    echo
-    if [[ $REPLY =~ ^[Yy]$ ]]
+  [[ -z "$RODENT_DISABLE_RC_SECURITY" ]] && {
+    if ! grep -Fxqs "$localdir" "$RODENT_HOME/local/trusted-paths"
     then
-      [[ -d "$RODENT_HOME/local" ]] || {
-        mkdir "$RODENT_HOME/local" || {
-          echo "failed to create $RODENT_HOME/local"
-          exit 1
+      echo "!!! Untrusted rodentrc found at $localdir !!!"
+      read -p "Trust location and load? " -n 1 -r
+      echo
+      if [[ $REPLY =~ ^[Yy]$ ]]
+      then
+        [[ -d "$RODENT_HOME/local" ]] || {
+          mkdir "$RODENT_HOME/local" || {
+            echo "failed to create $RODENT_HOME/local"
+            exit 1
+          }
         }
-      }
 
-      echo "$localdir" >> "$RODENT_HOME/local/trusted-paths" || {
-        echo "could not add localdir to trusted listing"
-      }
-    else
-      allow_local_rc=false
+        echo "$localdir" >> "$RODENT_HOME/local/trusted-paths" || {
+          echo "could not add localdir to trusted listing"
+        }
+      else
+        allow_local_rc=false
+      fi
     fi
-  fi
+  }
 
   if $allow_local_rc
   then
